-- ============================================================
-- V1: Adventure-KM database schema
-- Compatible with both H2 and PostgreSQL
-- ============================================================

-- 1. Users
CREATE TABLE users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR(50)  NOT NULL UNIQUE,
    email       VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    avatar_sprite_id INT      NOT NULL DEFAULT 1,
    role        VARCHAR(10)  NOT NULL DEFAULT 'USER',
    strava_token VARCHAR(500),
    coros_token  VARCHAR(500),
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_users_role CHECK (role IN ('USER', 'ADMIN'))
);

-- 2. Invitations
CREATE TABLE invitations (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token       VARCHAR(255) NOT NULL UNIQUE,
    email       VARCHAR(255) NOT NULL,
    invited_by  BIGINT       NOT NULL,
    used_at     TIMESTAMP,
    expires_at  TIMESTAMP    NOT NULL,

    CONSTRAINT fk_invitations_user FOREIGN KEY (invited_by) REFERENCES users (id)
);

-- 3. Adventures
CREATE TABLE adventures (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL,
    title       VARCHAR(255) NOT NULL,
    date        DATE         NOT NULL,
    content     TEXT,
    type        VARCHAR(10)  NOT NULL,
    difficulty  INT          NOT NULL,
    gpx_path    VARCHAR(500),
    status      VARCHAR(10)  NOT NULL DEFAULT 'DRAFT',
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_adventures_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT chk_adventures_type CHECK (type IN ('TRAIL', 'HIKE', 'ULTRA', 'RACE')),
    CONSTRAINT chk_adventures_difficulty CHECK (difficulty BETWEEN 1 AND 5),
    CONSTRAINT chk_adventures_status CHECK (status IN ('DRAFT', 'PUBLISHED'))
);

-- 4. Adventure stats
CREATE TABLE adventure_stats (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    adventure_id    BIGINT        NOT NULL UNIQUE,
    distance_km     DECIMAL(8,2)  NOT NULL,
    elevation_gain_m  INT         NOT NULL,
    elevation_loss_m  INT         NOT NULL,
    duration_minutes  INT,
    max_altitude_m    INT,
    min_altitude_m    INT,

    CONSTRAINT fk_stats_adventure FOREIGN KEY (adventure_id) REFERENCES adventures (id)
);

-- 5. Photos
CREATE TABLE photos (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    adventure_id BIGINT       NOT NULL,
    file_path    VARCHAR(500) NOT NULL,
    caption      VARCHAR(255),
    sort_order   INT          NOT NULL DEFAULT 1,
    uploaded_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_photos_adventure FOREIGN KEY (adventure_id) REFERENCES adventures (id),
    CONSTRAINT chk_photos_sort_order CHECK (sort_order BETWEEN 1 AND 5)
);

-- 6. Equipment items (catalog)
CREATE TABLE equipment_items (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(100) NOT NULL,
    category         VARCHAR(10)  NOT NULL,
    icon_key         VARCHAR(50),
    pixel_sprite_key VARCHAR(50),

    CONSTRAINT chk_equipment_category CHECK (category IN ('SHOES', 'VEST', 'POLES', 'HAT', 'GLASSES', 'BACKPACK', 'WATCH', 'OTHER'))
);

-- 7. Adventure ↔ Equipment (many-to-many)
CREATE TABLE adventure_equipment (
    adventure_id  BIGINT NOT NULL,
    equipment_id  BIGINT NOT NULL,

    PRIMARY KEY (adventure_id, equipment_id),
    CONSTRAINT fk_ae_adventure FOREIGN KEY (adventure_id) REFERENCES adventures (id),
    CONSTRAINT fk_ae_equipment FOREIGN KEY (equipment_id) REFERENCES equipment_items (id)
);

-- 8. User levels (RPG progression)
CREATE TABLE user_levels (
    user_id          BIGINT       PRIMARY KEY,
    total_km         DECIMAL(10,2) NOT NULL DEFAULT 0,
    total_elevation_m INT          NOT NULL DEFAULT 0,
    adventure_count  INT           NOT NULL DEFAULT 0,
    rpg_score        INT           NOT NULL DEFAULT 0,
    level            INT           NOT NULL DEFAULT 0,

    CONSTRAINT fk_levels_user FOREIGN KEY (user_id) REFERENCES users (id)
);
